# Generated by Django 2.1.3 on 2019-02-28 07:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2019, 2, 28, 12, 44, 57, 511903))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='auth.User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
