# Generated by Django 2.1.3 on 2019-02-28 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 12, 45, 13, 942482)),
        ),
    ]
