# Generated by Django 2.1.3 on 2019-02-28 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20190228_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ticketapp.Comment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 14, 47, 36, 885041)),
        ),
    ]
