# Generated by Django 2.1.5 on 2019-03-06 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20190306_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 15, 50, 38, 272376)),
        ),
    ]
