# Generated by Django 2.1.5 on 2019-03-06 10:39

import datetime
from django.db import migrations, models
import ticketapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_auto_20190306_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 16, 9, 52, 591607)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=ticketapp.models.Ticket.tid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
