# Generated by Django 2.1.5 on 2019-02-19 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.PositiveIntegerField()),
                ('reciever_id', models.PositiveIntegerField()),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2019, 2, 19, 12, 24, 16, 963668))),
                ('message', models.TextField()),
            ],
        ),
    ]
