# Generated by Django 2.1.5 on 2019-02-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chat',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
