# Generated by Django 2.1.5 on 2019-03-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20190307_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='Name',
        ),
    ]
