# Generated by Django 2.1.5 on 2019-02-11 08:09

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_No', models.CharField(max_length=128)),
                ('Title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Price', models.PositiveIntegerField()),
                ('Offer', models.PositiveIntegerField()),
                ('Brand', models.CharField(max_length=264)),
                ('catalog', models.CharField(max_length=264)),
                ('Size', models.CharField(max_length=50)),
                ('Weight_per_kg', models.PositiveIntegerField(default='1')),
                ('Category', models.CharField(max_length=264)),
                ('Sub_Category', models.CharField(max_length=264)),
                ('Product_Type', models.CharField(choices=[('Deals of the Day', 'Deals of the Day'), ('Latest Designer Dresses', 'Latest Designer Dresses'), ('Recommended by we', 'Recommended by we'), ('Top Rated Product', 'Top Rated Product')], max_length=100)),
                ('Quantity', models.CharField(max_length=128)),
                ('Product_Description', models.TextField(max_length=128)),
                ('Details', models.TextField(max_length=128)),
                ('Meta_Title', models.CharField(max_length=128)),
                ('Meta_Keyword', models.CharField(max_length=128)),
                ('Meta_Desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='make_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('user_full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.TextField(max_length=100)),
                ('shipping_user_full_name', models.CharField(max_length=50)),
                ('shipping_user_contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('client_gst', models.CharField(max_length=20)),
                ('mode_of_payment', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 11, 13, 39, 42, 706232))),
                ('shipping_cost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=6)),
                ('minvoice', models.ForeignKey(on_delete='DO_NOTHING', to='bbillsysapp.make_invoice')),
            ],
        ),
    ]
