# Generated by Django 2.1.5 on 2019-02-17 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0002_auto_20190214_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_invoice',
            name='barcode_number',
            field=models.CharField(default=345345234123, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='make_invoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 17, 2, 2, 57, 220388)),
        ),
    ]
