# Generated by Django 2.1.5 on 2019-02-21 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0003_auto_20190217_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=265)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Meta_Title', models.CharField(max_length=128)),
                ('Meta_Keyword', models.CharField(max_length=128)),
                ('Meta_Desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=264)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Meta_Title', models.CharField(max_length=128)),
                ('Meta_Keyword', models.CharField(max_length=128)),
                ('Meta_Desc', models.CharField(max_length=128)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbillsysapp.Prod_Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=265)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Meta_Title', models.CharField(max_length=128)),
                ('Meta_Keyword', models.CharField(max_length=128)),
                ('Meta_Desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=265)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Meta_Title', models.CharField(max_length=128)),
                ('Meta_Keyword', models.CharField(max_length=128)),
                ('Meta_Desc', models.CharField(max_length=128)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbillsysapp.Prod_Category')),
            ],
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbillsysapp.Prod_Brand'),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbillsysapp.Prod_Category'),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Sub_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbillsysapp.Prod_subcategory'),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbillsysapp.Prod_Catalog'),
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 21, 12, 53, 30, 776674)),
        ),
    ]
