# Generated by Django 2.1.5 on 2019-02-25 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0005_auto_20190221_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='Sub_Category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='prod_category',
            old_name='category',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 0, 52, 33, 139474)),
        ),
    ]
