# Generated by Django 2.1.5 on 2019-02-25 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0006_auto_20190225_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='subcategory',
            new_name='Sub_Category',
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 1, 12, 19, 70595)),
        ),
    ]
