# Generated by Django 2.1.5 on 2019-02-25 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0008_auto_20190225_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 25, 4, 22, 25, 384402)),
        ),
    ]
