# Generated by Django 2.1.5 on 2019-03-02 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0012_auto_20190302_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/'),
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 6, 28, 35, 130675)),
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='prod_brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_img/'),
        ),
        migrations.AlterField(
            model_name='prod_catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_img/'),
        ),
        migrations.AlterField(
            model_name='prod_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/'),
        ),
        migrations.AlterField(
            model_name='prod_subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcat_img/'),
        ),
    ]
