# Generated by Django 2.1.5 on 2019-03-03 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0014_auto_20190302_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_invoice',
            name='barcode_number',
        ),
        migrations.RemoveField(
            model_name='make_invoice',
            name='image',
        ),
        migrations.AddField(
            model_name='make_invoice',
            name='discount',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 3, 6, 2, 27, 409645)),
        ),
    ]
