# Generated by Django 2.1.5 on 2019-03-05 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0017_auto_20190305_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_store',
            old_name='store_id',
            new_name='store_no',
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 11, 40, 5, 503857)),
        ),
    ]
