# Generated by Django 2.1.5 on 2019-03-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbillsysapp', '0002_auto_20190305_1354'),
        ('bbillsysapp', '0019_auto_20190305_1321'),
    ]

    operations = [
    ]
