# Generated by Django 2.1.5 on 2019-03-07 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20190307_1109'),
        ('bbillsysapp', '0025_auto_20190306_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Employee')),
                ('select_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbillsysapp.create_store')),
            ],
        ),
        migrations.AlterField(
            model_name='make_invoice',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 7, 12, 41, 40, 431588)),
        ),
    ]
